Shader program and shader uniforms
cmlibs/zinc pull request #124
Opened 2018-10-04 00:36 UTC by alan-wu

Shader program and shader uniforms are now part of the Zinc APIs. Users can now utilise these APIs to access GLSL.

2018-10-04 23:13 UTC, rchristie requested changes
Very good; a few doxygen fixes needed. A couple of minor actual API changes.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/material.h
> + * Get the shaderuniforms object currently in used by the material.
typo: in use

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/material.h
> + * Get the shaderprogram object currently in used by the material.
typo: in use

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/scene.h
> + * Returns a handle to a shader module which manages shader objects
Change to:

    Get the shader module which manages material shader objects.

Use `the shader module` not `a shader module` as there is only one. The `@return` can describe handles etc.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/material.h
> + * @param shaderprogram  The shaderprogram to be set for this material.
Doc text should read `shader program` not `shaderprogram`.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/material.h
> + * @return  Handle to the shaderprogram, or NULL/invalid handle if none or failed.
Doc text should read `shader program` not `shaderprogram`.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/material.h
> + * Get the shaderuniforms object currently in used by the material.
Doc text should read `shader uniforms` not `shaderuniforms`. Also below and in next function.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * shader will belong to.
shader uniforms

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @param shaderuniforms  Handle to shaderuniforms.
shader uniforms, also in @return

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Destroys handle to the shaderuniforms (and sets it to NULL).
shader uniforms, also in @param

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Get managed status of shaderuniforms in its owning shader module.
shader uniforms, also in @param, @return

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Set managed status of shaderuniforms in its owning shader module.
shader uniforms, several times.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @param name  uniform with the matching name will be removed
`Name of uniform to be removed.`

Keep consistent with docs: start with capital, end in fullstop.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Remove a set of uniform from the uniforms object,
comma at end. Should this be 'Remove a set of uniform values'?

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @return  The size of unifomr , or 0 on error.
Typo uniform. How about:
`The actual number of values in the uniform, or 0 on error.`

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Add a new set of double precision uniform to the uniforms object,
Add a new set of double precision uniform values to the uniforms object. This set...

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @param values  Initial values to be set for the uniform.
Should be `valuesIn`

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * the specified name. This will not change the size of the uniform.
Clarify if it is an error if a different size is passed in, or a uniform of that name is not found.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @param values  Array containing values to be set for the uniform.
`valuesIn`

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> +ZINC_API int cmzn_shaderuniforms_get_uniform_double(cmzn_shaderuniforms_id shaderuniforms,
`double` or `real`? Is single possible? What do we get from Python?

All other Zinc APIs use `real`...

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @return  The size of unifomr , or 0 on error.
Typo. see double variant.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Add a new set of double precision uniform to the uniforms object,
Add a new set of integer uniform values to the uniforms object. This set ...

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * If an uniform with the same name already exist, nothing will be added to the
exists

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @param values  Initial values to be set for the uniform.
valuesIn. check other APIs.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * the specified name. This will not change the size of the uniform.
See comments for double variant (error conditions). Is it an error to change between double and integer?

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * @param name  The name of the shader uniforms.
The name of the shader program.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * Create and return a new shader uniforms.
Fik cut & paste errors calling program 'uniforms' in this and following.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> +
Remove extra blank line :-)

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> +ZINC_API char *cmzn_shaderprogram_get_vertex_string(cmzn_shaderprogram_id shaderprogram);
In get/set vertex/fragment APIs I think the names should be qualified with 'shader' to say what it is e.g. get_vertex_shader.
Remove 'string' as redundant.
sp.setVertexShader(...)
sp.setFragmentShader(...)

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> + * string will be compiled at run time if no error is encounter.
encountered. Same for get_fragment_shader.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.h
> +ZINC_API int cmzn_shaderprogram_set_vertex_string(cmzn_shaderprogram_id shaderprogram,
Documentation should state the format is GLSL, since only OpenGL rendering is currently supported by Zinc.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.hpp
> +	char *getVertexString()
{get|set}{Vertex|Fragment}Shader

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/shader.hpp
> +	int getUniformDouble(const char *name, int valuesCount, double *valuesOut)
As per previous comment: Double or Real?

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/types/shaderid.h
> + * @brief Zinc shader uniforms provide an object to wor with
Typo 'wor' and 'mataching' below.

Specify that uniforms provide named numerical argument values, from scalar to 4-component vectors for supplying to shader programs.

2018-10-04 23:13 UTC, rchristie commented on core/source/api/opencmiss/zinc/types/shaderid.h
> + * fragment shader.
Suggest:
A Zinc shader program object manages OpenGL shader programs to be passed to the GPU / rendering pipeline. It allows specification of vertex and fragment shaders which when applied to a material, optionally with a set of shader uniforms, affects vertex positions/values and fragment colour and lighting to create special effects.

2018-10-09 02:51 UTC, alan-wu commented
I agreed with the review and made the suggested changes.

2018-10-09 03:12 UTC, rchristie approved these changes
Good stuff.

2018-10-09 03:15 UTC, merged

2018-10-09 22:17 UTC, alan-wu commented
Closes #122