Add material json description serialisation
cmlibs/zinc pull request #181
Opened 2021-08-10 06:22 UTC by rchristie

Closes issue #176.
Closes issue #154.

2021-08-25 09:16 UTC, hsorby requested changes
A minor change, and a query about he default surface material should it be defined like default material and default selected material are?  Is it set in the initialisation of the material module?

2021-08-25 09:16 UTC, hsorby commented on src/graphics/material.cpp
> +		/*shininess*/0.0 },
Should this be a semicolon here?

2021-08-25 20:49 UTC, rchristie commented on src/graphics/material.cpp
> +		/*shininess*/0.0 },
It is legal, but I don't like multiple assignments when declaring variables (like int a=1, b=2;) , especially not with structures in this way. I'll tidy it up.

2021-08-25 20:58 UTC, rchristie commented
> A minor change, and a query about he default surface material should it be defined like default material and default selected material are? Is it set in the initialisation of the material module?

The default surface material is initially null which gives the older behaviour where the default material is used. I added it so that when we make the default material black (good for lines on a white background), a different default may be used for surfaces and contours. Note I'm referring to the default material attributes of the Material module here, not the material called 'default'.
If we can come up with a better plan for these it can be added in this PR.

2021-08-26 00:31 UTC, alan-wu requested changes

2021-08-26 00:31 UTC, alan-wu commented on src/description_io/material_json_io.hpp
> +#define TESSELLATION_JSON_IO_HPP
Surely this is not meant to be tessellation.

2021-08-26 00:31 UTC, alan-wu commented on src/description_io/material_json_io.hpp
> +#define TESSELLATION_JSON_IO_HPP
I would be surprised if both exports work at the same time.

2021-08-26 01:29 UTC, rchristie commented on src/description_io/material_json_io.hpp
> +#define TESSELLATION_JSON_IO_HPP
Fixed.

2021-08-26 01:30 UTC, rchristie commented on src/graphics/material.cpp
> +		/*shininess*/0.0 },
Tidied up code for defining default and standard materials.

2021-08-26 01:33 UTC, hsorby approved these changes

2021-08-26 02:13 UTC, alan-wu approved these changes

2021-08-26 02:22 UTC, merged