Update to new dependencies, fix memory leaks
cmlibs/zinc pull request #254
Opened 2022-12-09 01:48 UTC by hsorby

2022-12-14 00:51 UTC, rchristie requested changes
Great work, though some of the reorgs (e.g. to tests, which are good improvements) would have been better left till later, but we'll cope.
There are some things I've picked up - please read the individual comments.
The request list includes reverting tabs to spaces in the 7 or so files which were too hard to diff as a result.

BTW I'm **mostly** OK with making the full conversion to 4 spaces (but not right now), conditions being:
1. We have cleared all the current PRs so are in "quiet patch" and all agree to the plan & timing.
2. We make the changes from a neutral user account (either from a branch in/as cmlibs organisation or a special "joe whitespace" user), so it doesn't distort code contributions statistics.

2022-12-14 00:51 UTC, rchristie commented on CMakeLists.txt
> +    set(ZINC_PACKAGE_CONFIG_DIR "share/cmake/ZINC")
Check case of folder.

2022-12-14 00:51 UTC, rchristie commented on cmake/EnvironmentChecks.cmake
> +if(VALGRIND_EXE AND Python_Interpreter_FOUND)
How do we use python with valgrind?

2022-12-14 00:51 UTC, rchristie commented on src/context/context.cpp
> +    cmzn_logger::deaccess(logger);
this->logger

2022-12-14 00:51 UTC, rchristie commented on src/finite_element/finite_element.cpp
> +#include <math.h>
```
#include <cmath>
```
And list alphabetically for new name.

2022-12-14 00:51 UTC, rchristie commented on src/finite_element/finite_element.cpp
> +    delete previous_element_values;
There's another DEALLOCATE(previous_element_values) earlier (line 5121) which also needs to change to delete.
Annoyingly github doesn't let me put comments on lines you haven't touched.

2022-12-14 00:51 UTC, rchristie commented on src/finite_element/finite_element_field_parameters.cpp
> +            cmzn_nodeiterator_destroy(&nodeIter);
This is a bad lapse on my part, and the fix works.
Firstly, the iterator is derived from RefCounted so the most efficient cleanup is cmzn::Deaccess (look at the implementation of cmzn_nodeiterator_destroy().
We should consider adding a template class that cleans up RefCounter derived objects by calling their Deaccess at end of scope; but this is getting very smart pointer like.
In the absence of this, and when I notice these issues, I fall back to a single return path by storing a "result" and break/exit the loop if it is no longer CMZN_OK.

2022-12-14 00:51 UTC, rchristie commented on src/finite_element/finite_element_mesh.hpp
> +            elementVectorDOFs.clear();
It doesn't look like these are needed here as the block_array/dynarray_block_array should call clear() in their virtual destructors. Can you see if removing them doesn't leave a leak?

2022-12-14 00:51 UTC, rchristie commented on src/finite_element/finite_element_nodeset.cpp
> +        if (this->nodeset) {
Format: squiggly bracket on next line.

2022-12-14 00:51 UTC, rchristie commented on src/finite_element/finite_element_nodeset.cpp
> +    }
This is not the cause of the leak.
Something else has leaked an access to one or more FE_node_field_info in this list.
At the time this is called, all nodes should be invalidated and not have a field info pointer, so it must be another function.
I think I've found one place which leaks a reference (can look for more if there are still issues):
FE_node_template *FE_nodeset::create_FE_node_template()
It's call to this->get_FE_node_field_info adds an access; need to store locally and deaccess as the called function also adds an access.

What you have is possibly safe & it's on the to-do list to remove all this shared node field info stuff.

2022-12-14 00:51 UTC, rchristie commented on src/graphics/material.cpp
> +            cmzn_field_image_destroy(&image_field);
If null material is passed to this function but a valid image field/texture is supplied, this will leak a reference in the other return path.
I suggest doing the image field cast after checking material argument and nest the rest one level deeper.

2022-12-14 00:51 UTC, rchristie commented on src/minimise/optimisation.cpp
> +
Remove.

2022-12-14 00:51 UTC, rchristie commented on src/stream/stream_private.hpp
>  		memory_block->to_be_deallocated = 1;
This would be better handled by a memory_block method e.g. setBufferCopy or setBufferReference depending on how it's mean to work.
But it's a bit weird that it's passing in a memory_buffer_reference and sets to_be_deallocated to 1. Perhaps it should be virtual and the cmzn_streamresource_memory_copy overrides to copy buffer?

2022-12-14 00:51 UTC, rchristie commented on tests/fieldmodule/fieldimage.cpp
> +    EXPECT_EQ(CMZN_OK, result = cmzn_field_image_read_file(im, fixedPath.c_str()));
Proper path needed -- not hsor001.

2022-12-14 00:51 UTC, rchristie commented on tests/fieldio/ex_io.cpp
> -	ZincTestSetupCpp zinc;
Please undo tabs to spaces on the unmodified lines in this file... diff is impossible.

2022-12-14 00:51 UTC, rchristie commented on tests/optimisation/optimisationtests.cpp
> +//TEST(cmzn_optimisation, arguments)
Please uncomment these tests so they run.

2022-12-14 00:51 UTC, rchristie commented on tests/graphics/tests.cmake
> +#    ${CURRENT_TEST}/tessellation.cpp
Please uncomment tests and ensure they run.

2022-12-14 00:51 UTC, rchristie commented on tests/graphics/scene.cpp
> -	ZincTestSetup zinc;
Please restore tabs to enable diff/review.

2022-12-14 00:51 UTC, rchristie commented on tests/fieldmodule/region_io.cpp
> -	cmzn_context_id context = cmzn_context_create("test");
Please restore tabs to diff/review.

2022-12-14 00:51 UTC, rchristie commented on tests/fieldmodule/fieldparameterstests.cpp
> -	ZincTestSetupCpp zinc;
Please restore tabs for diff/review.

2022-12-14 00:51 UTC, rchristie commented on tests/fieldmodule/finiteelement.cpp
> -	EXPECT_EQ(RESULT_OK, result = zinc.root_region.readFile(TestResources::getLocation(TestResources::FIELDMODULE_EX2_CUBE_NODE_ELEMENT_GRID_RESOURCE)));
Please restore tabs for diff/review.

2022-12-14 02:49 UTC, hsorby commented on cmake/EnvironmentChecks.cmake
> +if(VALGRIND_EXE AND Python_Interpreter_FOUND)
We use a Python script that wraps the use of valgrind making the output much easier to understand (for me anyway).

2022-12-15 05:02 UTC, hsorby commented on src/finite_element/finite_element_mesh.hpp
> +            elementVectorDOFs.clear();
Removing them did cause a leak, maybe another not deaccessing from the correct location situation?

2022-12-15 06:03 UTC, rchristie commented on src/finite_element/finite_element_mesh.hpp
> +            elementVectorDOFs.clear();
I think these are likely safe so keep your fixes; just raise an issue to investigate as suggests virtual destructors are not being called as expected & link to this code.

2023-01-26 09:42 UTC, rchristie requested changes
Really great work. A very small number of changes noted in remaining comments.
I have briefly run interactive mapclient with Scaffold Creator and Field Fitter, and both worked fine; I will continue to test some other libraries and plugins, but for now I'm happy with the code changes pending these small fixes.

2023-01-26 09:42 UTC, rchristie commented on src/context/context.cpp
> +        cmzn_region::deaccess(region);
This line should be removed; it probably only works because all the regions happen to have been destroyed before the context in all our tests. The regions aren't accessed in the allRegions list so they are destroyed when last dereferenced. Only the defaultRegion is accessed & sticks around.
I attempted to make a test for this case, but it isn't likely to be triggered because cmzn_region::deaccess uses == 0, not <= 0. Test case was:
```
TEST(cmzn_context, region_lifetime)
{
	cmzn_context_id context = cmzn_context_create("test");
	cmzn_region_id region = cmzn_context_create_region(context);
	cmzn_context_destroy(&context);
	cmzn_region_destroy(&region);
}
```
The above test only proves correct behaviour if you also change cmzn_region::deaccess as decribed in later comment.

2023-01-26 09:42 UTC, rchristie commented on src/region/cmiss_region.hpp
> +        }
This is incorrect; need to clear region in all cases, not just when access_count <=0.
I would use the original code with <= 0 (but add {} brackets) as it's at least 50% likely the extra delete will be triggered by additional deaccesses and thereby catch erroneous behaviour. Also need changes mentions in context.cpp.

2023-01-26 09:42 UTC, rchristie commented on src/graphics/material.cpp
> +            }
This leaks the image_field if texture_number not in [1,2,3,4].
Simplest fix is to put cmzn_field_image_destroy(&image_field); outside the brackets it's in, and use a return_code variable instead of multiple return paths.

2023-01-26 09:42 UTC, rchristie commented on src/region/cmiss_region.cpp
> +//	this->region = nullptr;
I think this should be cleared.

2023-01-26 09:42 UTC, rchristie commented on tests/fieldio/fieldml_basic.cpp
> +//	checkVariableNodeVersionsWithTime2d(fm2);
Uncomment and test.

2023-01-26 09:42 UTC, rchristie commented on tests/optimisation/tests.cmake
> +SET("data/fit_line_time.exf" "${CMAKE_CURRENT_LIST_DIR}/data/fit_line_time.exf")
The last line is probably an accidental replace, but are all these lines redundant now (in all test.cmake files)?

2023-01-26 09:42 UTC, rchristie commented on tests/region/region.cpp
> +    free(tmpText);
Should these calls to free(tmpText) be:
cmzn_deallocate(tmpText);

2023-01-26 22:07 UTC, rchristie commented
It's looking good, just testing how it builds and runs for me; would you mind also removing the hsor001 paths in comments in value.h? I don't know when they are from.

2023-01-26 22:24 UTC, hsorby commented
Removed those, would have been from the big split 10 years ago.

2023-01-26 23:01 UTC, rchristie approved these changes
Great stuff. Happy with the code, builds and tests fine in Zinc and SwigZinc and have run at least Scaffold Creator.
However, I'm still trying to run python lib tests, so will contact you on Slack.

2023-01-27 00:05 UTC, merged